site_name: Build your code-first agent with Azure AI Foundry

nav:
  - ã¯ã˜ã‚ã«: index.md
  - ã‚½ãƒªãƒ¥ãƒ¼ã‚·ãƒ§ãƒ³ã‚¢ãƒ¼ã‚­ãƒ†ã‚¯ãƒãƒ£ãƒ¼: architecture.md
  - ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£ã«é–¢ã™ã‚‹æ‡¸å¿µäº‹é …: security.md
  - Getting Started: getting-started.md
  # - Workshop Setup:
  #   - BUILD Attendees: introduction-event.md
  #   - Self-Guided Learners: introduction-self-guided.md
  - Lab 1ğŸš€Function Calling ã®ãƒ‘ãƒ¯ãƒ¼: lab-1-function_calling.md
  - Lab 2ğŸš€ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆã®ã‚°ãƒ©ã‚¦ãƒ³ãƒ‡ã‚£ãƒ³ã‚°: lab-2-file_search.md
  - Lab 3ğŸš€ã‚³ãƒ¼ãƒ‰ã‚¤ãƒ³ã‚¿ãƒ¼ãƒ—ãƒªã‚¿ãƒ¼å…¥é–€: lab-3-code_interpreter.md
  - Lab 4ğŸš€Grounding with Bing Search: lab-4-bing_search.md
  - Lab 5ğŸš€å¤šè¨€èªã§ã®è¦–è¦šåŒ–: lab-5-multilingual.md
  - Lab 6ğŸš€æœ€å¾Œã«: finishing-up.md
  - ã¾ã¨ã‚: summary.md
  - ãƒªã‚½ãƒ¼ã‚¹æƒ…å ±: resources.md
  # - Deployment: deployment.md
  # - Troubleshooting: troubleshooting.md


plugins:
  - glightbox
  - include-markdown

theme:
  name: material
  logo: media/favicon.png
  favicon: media/favicon.png
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - navigation.tabs.sticky 
    - content.tabs.link

  # Change Font: https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/?h=fonts
  # Google Fonts Supported By Default: https://fonts.google.com/
  font:
    code: Roboto Mono #Monospaced
    text: Roboto #Regular
  # logo: docs/media/azure-ai-studio.svg
  palette:
    - scheme: default  # Light Mode
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate # Dark Mode
      primary: amber
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to light mode


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  # - pymdownx.emoji:
      # emoji_index: !!python/name:material.extensions.emoji.twemoji
      # emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_css:
  - css/custom.css

# mkdocs.yml
extra_javascript:
  - js/custom-nav.js
